version: '3.8'

services:
      
  rabbit-mq:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: rabbitmq:3.9-management
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    networks:
      - 41scj-microservices
      
  db-mysql:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=asd123qwe!
    entrypoint:
      sh -c "echo 'CREATE DATABASE IF NOT EXISTS 41scj_ms_usuarios; CREATE DATABASE IF NOT EXISTS 41scj_ms_notificacoes;' > /docker-entrypoint-initdb.d/init.sql; /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - 3306:3306
    networks:
      - 41scj-microservices
            
  eureka-server:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: emersondiaspd/eureka-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - 41scj-microservices
      
  config-server:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: emersondiaspd/config-server:0.0.1-SNAPSHOT
    ports:
      - 8888:8888
    networks:
      - 41scj-microservices
      
  api-gateway:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: emersondiaspd/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICE_URL.
      : http://eureka-server:8761/eureka
    networks:
      - 41scj-microservices
      
  notificacoes-service:
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: emersondiaspd/notificacoes-service:0.0.1-SNAPSHOT
    restart: always
    build:
      context: .
      dockerfile: notificacoes-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING.CONFIG.IMPORT: optional:configserver:http://config-server:8888/
      EUREKA.CLIENT.SERVICE_URL.DEFAULTZONE: http://eureka-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING.DATASOURCE.URL: jdbc:mysql://db-mysql:3306/41scj_ms_notificacoes?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: asd123qwe!
      SPRING.FLYWAY.URL: jdbc:mysql://db-mysql:3306/41scj_ms_notificacoes?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: asd123qwe!
    ports:
      - 8082:8082
    depends_on:
      - config-server
      - eureka-server
      - db-mysql
      - rabbit-mq
    networks:
      - 41scj-microservices
      
  usuarios-service:
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: emersondiaspd/usuarios-service:0.0.1-SNAPSHOT
    restart: always
    build:
      context: .
      dockerfile: usuarios-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING.CONFIG.IMPORT: optional:configserver:http://config-server:8888/
      EUREKA.CLIENT.SERVICE_URL.DEFAULTZONE: http://eureka-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING.DATASOURCE.URL: jdbc:mysql://db-mysql:3306/41scj_ms_usuarios?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: asd123qwe!
      SPRING.FLYWAY.URL: jdbc:mysql://db-mysql:3306/41scj_ms_usuarios?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: asd123qwe!
    ports:
      - 8083:8083
    depends_on:
      - config-server
      - eureka-server
      - db-mysql
      - rabbit-mq
    networks:
      - 41scj-microservices
      
networks:
  41scj-microservices:
    external: true

        
