server:
  port: 8082 #'${PORT:0}'
  forward-headers-strategy: framework
  
eureka:
#  instance:
#    instance-id: >-
#      ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
      
spring:
  application:
    name: notificacoes-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: default
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/41scj_ms_notificacoes?useTimezone=true&serverTimezone=UTC
    username: root
    password: asd123qwe!
    
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  flyway:
    url: jdbc:mysql://localhost:3306/41scj_ms_notificacoes?useTimezone=true&serverTimezone=UTC
    user: root
    password: asd123qwe!
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*' 
        
springdoc:
  #show-actuator: true
  api-docs:
    path: notificacoes/v3/api-docs
