server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:  
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: usuarios-service
        uri: lb://usuarios-service
        predicates:
        - Path=/usuarios/**
      - id: notificacoes-service
        uri: lb://notificacoes-service
        predicates:
        - Path=/notificacoes/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
