server:
  port: ${PORT:8765}

eureka:
  client:
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${FETCH_REGISTRY:true}
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOST_NAME:${spring.application.name}}  # work on swarm
    preferIpAddress: ${PREFER_IP_ADDRESS:false}
    # enable to register multiple app instances with a random server port
    instance-id: >-
      ${spring.application.name}:${spring.application.instance_id:${random.value}}

#eureka:
#  client:
#    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
#    fetchRegistry: ${FETCH_REGISTRY:false}
#    service-url:
#      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
#  instance:
#    hostname: ${HOST_NAME:${spring.application.name}}  # work on swarm
#    preferIpAddress: ${PREFER_IP_ADDRESS:false}
#    # enable to register multiple app instances with a random server port
#    instance-id: >-
#      ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    leaseRenewalIntervalInSeconds: ${LEASE_RENEWAL_INTERVAl_IN_SECONDS:10}
#    leaseExpirationDurationInSeconds: ${LEASE_EXPIRATION_DURATIONIN_SECONDS:20}
       
spring:
  application:
    name: api-gateway
#  config:
#    import: optional:configserver:http://localhost:8888/
  cloud:  
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: usuarios-service
        uri: lb://usuarios-service
        predicates:
        - Path=/usuarios/**
      - id: notificacoes-service
        uri: lb://notificacoes-service
        predicates:
        - Path=/notificacoes/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

