server:
  port: 8765

eureka:
  instance:
    instance-id: >-
      ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    leaseRenewalIntervalInSeconds: 1
  client:
    service-url:
      defaultZone: http://192.168.15.200:8761/eureka
       
spring:
  application:
    name: api-gateway
#  config:
#    import: optional:configserver:http://192.168.15.200:8888/
  cloud:  
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: usuarios-service
        uri: lb://usuarios-service
        predicates:
        - Path=/usuarios/**
      - id: notificacoes-service
        uri: lb://notificacoes-service
        predicates:
        - Path=/notificacoes/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
