server:
  port: '${PORT:0}'
eureka:
  instance:
    instance-id: >-
      ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    
spring:
  application:
    name: veiculos-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_veiculos?useTimezone=true&serverTimezone=UTC
    username: root
    password: asd123qwe!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: ms_veiculos
    user: root
    password: asd123qwe!
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'     
springdoc:
  api-docs:
    path: veiculos-service/v3/api-docs  
