server:
  port: 8080 #'${PORT:0}'
eureka:
  instance:
    instance-id: >-
      ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
spring:
  application:
    name: parceiros-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_parceiros?useTimezone=true&serverTimezone=UTC
    username: root
    password: asd123qwe!
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: ms_parceiros
    user: root
    password: asd123qwe!      
management:
  endpoints:
    web:
      exposure:
        include:
        - '*' 
springdoc:
  #show-actuator: true
  api-docs:
    path: parceiros-service/v3/api-docs
