spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/41scj_ms_notificacoes?useTimezone=true&serverTimezone=UTC
    username: root
    password: asd123qwe!
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: 41scj_ms_notificacoes
    user: root
    password: asd123qwe!   
    
twilio:
  account:
    sid: AC390f0cfe0707a069223009ca9b53fa9b
    phone: '+18383843998'
  auth:
    token: 515891d6eabf6a0a76481a1287f0ce50
    
slack:
  bot:
    token: xoxb-779642959680-3012066368806-yLo7W0LprOKEzm44p9ISK6K1
    channel: C02N6UUS9AQ
    
queue:
  sms:
    name: SMSQueue
     
