server:
  port: ${PORT:8761}
  
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
#    register-with-eureka:  false
#    fetch-registry: false

eureka:
  client:
   register-with-eureka:  false
   fetch-registry: false
  instance:
    hostname: ${HOST_NAME:localhost}
    appname: eureka-server
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
    
