server:
  port: 8888

#eureka:
#  instance:
#    instance-id: >-
#      ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    service-url:
#      defaultZone: http://192.168.15.200:8761/eureka 
      
# Configurações para acessar o File Systems
#spring:
#  application:
#    name: config-server
#  profiles: 
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/microservices-configs
          
# Configurações para acessar um repositório na nuvem (GitHub)
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/diasRibeirao/41scj-microservices-dev-configs
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}
          default-label: master
          search-paths:
          - '*-service'
          clone-on-start: true
          
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka          
