name: Continous Integration with GitHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          
      - name: Build Eureka Server Container Image
        working-directory: ./eureka-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build API Gateway Container Image
        working-directory: ./api-gateway
        run: mvn spring-boot:build-image -DskipTests
      
      - name: Build Usuario Service Jar
        working-directory: ./usuarios-service
        run: mvn clean package -DskipTests
      
      - name: Build Notificacoes Service Jar
        working-directory: ./notificacoes-service
        run: mvn clean package -DskipTests
      
      - name: Docker Compose Build
        working-directory: ./
        run: docker-compose build
        
      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/usuarios-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/usuario-service:0.0.1-SNAPSHOT
          docker tag ${{ secrets.DOCKER_USERNAME }}/notificacoes-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/notificacoes-service:0.0.1-SNAPSHOT
          docker tag ${{ secrets.DOCKER_USERNAME }}/eureka-server:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/eureka-server:0.0.1-SNAPSHOT
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/api-gateway:0.0.1-SNAPSHOT
          docker tag ${{ secrets.DOCKER_USERNAME }}/config-server:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/config-server:0.0.1-SNAPSHOT
          docker push ${{ secrets.DOCKER_USERNAME }}/usuarios-service:0.0.1-SNAPSHOT
          docker push ${{ secrets.DOCKER_USERNAME }}/notificacoes-service:0.0.1-SNAPSHOT
          docker push ${{ secrets.DOCKER_USERNAME }}/eureka-server:0.0.1-SNAPSHOT
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:0.0.1-SNAPSHOT
          docker push ${{ secrets.DOCKER_USERNAME }}/config-server:0.0.1-SNAPSHOT
        
        
        
        
          
          
